name: My first workflow

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "👋 Hello world from my first workflow!"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - run: echo "The repo ${{ github.repository }} has the following files:"
          tree
